[package]
name = "youtube-irc-bot"
version = "1.4.1"
repository = "https://github.com/video-archivist/youtube-irc-bot"
license = "ISC"
edition = "2018"

[dependencies]
irc = "0.13.6"
tokio-core = "0.1.17"
htmlescape = "0.3.1"
time = "0.1.40"
docopt = "1.0.1"
serde = "1.0.79"
serde_derive = "1.0.79"
itertools = "0.7.8"
regex = "1.1.0"
lazy_static = "1.1.0"
failure = "0.1.2"
reqwest = "0.9.8"
mime = "0.3.9"
humansize = "1.1.0"
unicode-segmentation = "1.2.1"
toml = "0.4.8"
directories = "1.0.2"
url = "1.7.2"
dirs = "1.0.4"
